# Generated by Django 4.0.4 on 2022-04-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('publishedDate', models.IntegerField()),
                ('ISBN', models.CharField(max_length=50)),
                ('pageCount', models.IntegerField(default=0)),
                ('previewLink', models.URLField(blank=True, null=True)),
                ('language', models.CharField(blank=True, default='PL', max_length=5)),
                ('created', models.DateField(auto_now=True)),
                ('authors', models.ManyToManyField(to='book.author')),
            ],
        ),
    ]
